-- MySQL Script generated by MySQL Workbench
-- Sat Aug 11 15:30:31 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema zyka
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema zyka
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zyka` DEFAULT CHARACTER SET utf8 ;
USE `zyka` ;

-- -----------------------------------------------------
-- Table `zyka`.`samples`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zyka`.`samples` (
  `sampleId` VARCHAR(9) NOT NULL,
  `host` VARCHAR(15) NULL,
  `region` VARCHAR(20) NULL,
  `collectDate` DATE NULL,
  `fullSeq` TEXT(3700) NULL,
  PRIMARY KEY (`sampleId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zyka`.`pdbs_names_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zyka`.`pdbs_names_list` (
  `pdbName` VARCHAR(6) NOT NULL,
  `pdbNameId` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`pdbNameId`),
  UNIQUE INDEX `pdbName_UNIQUE` (`pdbName` ASC));


-- -----------------------------------------------------
-- Table `zyka`.`pdbs_nodes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zyka`.`pdbs_nodes` (
  `nodeId` VARCHAR(15) NULL DEFAULT NULL,
  `chain` VARCHAR(3) NULL DEFAULT NULL,
  `position` INT NULL DEFAULT NULL,
  `residue` VARCHAR(5) NULL DEFAULT NULL,
  `dssp` VARCHAR(5) NULL DEFAULT NULL,
  `degree` INT NULL DEFAULT NULL,
  `bfactorCa` FLOAT NULL DEFAULT NULL,
  `x` FLOAT NULL DEFAULT NULL,
  `y` FLOAT NULL DEFAULT NULL,
  `z` FLOAT NULL DEFAULT NULL,
  `pdbFileName` VARCHAR(20) NULL DEFAULT NULL,
  `rapdf` FLOAT NULL DEFAULT NULL,
  `tap` FLOAT NULL DEFAULT NULL,
  `accessibility` FLOAT NULL DEFAULT NULL,
  `pdbName` VARCHAR(6) NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  INDEX `pdbName_idx` (`pdbName` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `pdbName`
    FOREIGN KEY (`pdbName`)
    REFERENCES `zyka`.`pdbs_names_list` (`pdbName`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zyka`.`pdbs_edges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zyka`.`pdbs_edges` (
  `nodeId1` VARCHAR(15) NULL,
  `interaction` VARCHAR(15) NULL DEFAULT NULL,
  `nodeId2` VARCHAR(15) NULL DEFAULT NULL,
  `distance` FLOAT NULL DEFAULT NULL,
  `angle` FLOAT NULL DEFAULT NULL,
  `energy` FLOAT NULL DEFAULT NULL,
  `atom1` VARCHAR(5) NULL DEFAULT NULL,
  `atom2` VARCHAR(5) NULL DEFAULT NULL,
  `donor` VARCHAR(15) NULL DEFAULT NULL,
  `positive` VARCHAR(15) NULL DEFAULT NULL,
  `cation` VARCHAR(15) NULL DEFAULT NULL,
  `orientation` VARCHAR(15) NULL DEFAULT NULL,
  `pdbName` VARCHAR(6) NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zyka`.`cover`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zyka`.`cover` (
  `idcover` INT NOT NULL,
  `protein` VARCHAR(6) NULL,
  `sampleId` VARCHAR(9) NULL,
  `cover` FLOAT NULL,
  PRIMARY KEY (`idcover`),
  INDEX `sampleId_idx` (`sampleId` ASC),
  INDEX `proteinId_idx` (`protein` ASC),
  CONSTRAINT `sampleId`
    FOREIGN KEY (`sampleId`)
    REFERENCES `zyka`.`samples` (`sampleId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `proteinId`
    FOREIGN KEY (`protein`)
    REFERENCES `zyka`.`pdbs_names_list` (`pdbName`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zyka`.`aligned_samples`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zyka`.`aligned_samples` (
  `nodeId` VARCHAR(15) NULL,
  `proteinId` VARCHAR(6) NULL,
  `sampleId` VARCHAR(9) NULL,
  `nodeIndex` INT NULL,
  INDEX `proteinId_idx` (`proteinId` ASC),
  INDEX `sampleId_idx` (`sampleId` ASC),
  CONSTRAINT `alignedProteinId`
    FOREIGN KEY (`proteinId`)
    REFERENCES `zyka`.`pdbs_names_list` (`pdbName`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `alignedSampleId`
    FOREIGN KEY (`sampleId`)
    REFERENCES `zyka`.`samples` (`sampleId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
